utra-robosoccer/soccerbot

foundation/CMakeLists.txt, foundation/include/geometry/point2.hpp, foundation/include/geometry/point3.hpp, foundation/include/geometry/segment2.hpp, foundation/include/geometry/segment3.hpp, foundation/package.xml, foundation/src/geometry/point2.cpp, foundation/src/geometry/point3.cpp, foundation/src/geometry/segment2.cpp, foundation/src/geometry/segment3.cpp, foundation/tests/geometry/test_geometry.cpp, omnibot/omnibot_hardware/package.xml
converted matlab functions to c++
=> Nn geometry library

soccer_hardware/src/soccer_communication/Comm.py, soccer_hardware/src/soccer_communication/Receiver.py, soccer_hardware/src/soccer_communication/Transmitter.py, soccer_hardware/src/soccer_communication/utility.py
Fix the python static analysis alerts in our codebase.
=> Fix LGTM alerts

soccer_description/config/soccerbot_control.yaml, soccer_description/models/parameters.xacro, soccerbot/launch/modules/simulation.launch, soccerbot/launch/publish_standing_pose.launch, soccerbot/launch/soccerbot.launch
=> Nn standing

soccer_common/CMakeLists.txt, soccer_control/CMakeLists.txt, soccer_description/CMakeLists.txt, soccer_description/models/soccerbot.xacro, soccer_embedded/CMakeLists.txt, soccer_fieldline_detection/CMakeLists.txt, soccer_fieldline_detection/package.xml, soccer_fieldline_detection/src/soccer_fieldline_detector.cpp, soccer_geometry/CMakeLists.txt, soccer_hardware/CMakeLists.txt, soccer_hardware/package.xml, soccer_msgs/CMakeLists.txt, soccer_strategy/CMakeLists.txt, soccer_strategy/src/fall_detector.py, soccer_strategy/src/main.py, soccer_trajectories/CMakeLists.txt, soccer_trajectories/package.xml, soccer_trajectories/setup.py, soccerbot/CMakeLists.txt, soccerbot/launch/modules/localization.launch, soccerbot/launch/soccerbot.launch, soccerbot/package.xml
work in progress, not ready for merg
=> Ros noetic migration

.travis.yml, soccer_hardware/package.xml
Attempt at bumping CI server build configs
=> CI Config Upgrade/Fix

soccer_fieldline_detection/src/ball_detector.cpp, soccer_object_detection/src/object_detect_node.py
quick patches to get things working for mock competition
=> Publish Detected Robot Poses and Ignore Small Bounding Boxes

soccer_object_detection/src/main.py, soccer_object_detection/src/my_dataset.py, soccer_object_detection/src/train.py, soccer_object_detection/src/util.py
- For Nam's Object Detection Code:
- Added tqdm library  (not used at the moment) to add a progress bar in the future.
- Fixed a bug with the weights not being initialized as floats in test_model().
- Implemented a feature in display_dataset() to destroy windows after a certain delay to prevent freezing code.
=> Object Detection Update/Fixes

soccer_pycontrol/src/soccer_pycontrol/path.py, soccer_pycontrol/src/soccer_pycontrol/path_section_short.py, soccer_pycontrol/src/soccer_pycontrol/test.py
The pathing quick change cannot be changing too much specifically
- short paths
=> Fix small path

soccer_common/CMakeLists.txt, soccer_msgs/CMakeLists.txt, soccer_msgs/package.xml, soccer_object_detection/CMakeLists.txt, soccer_object_localization/CMakeLists.txt, soccer_strategy/CMakeLists.txt, soccerbot/CMakeLists.txt
All catkin_lint errors so far has been fixed.
=> fixing catkin_lint errors

.dockerignore, .prettierignore, Dockerfile, docker-compose.override.yaml, docker-compose.yaml
See the changes added here instructions for setup
https://github.com/utra-robosoccer/soccerbot/wiki/Setup-(Pycharm)
=> Allow debugging in the container

.dockerignore, .prettierignore, Dockerfile, docker-compose.override.yaml, docker-compose.yaml
Reverts utra-robosoccer/soccerbot#460
=> Revert "Allow debugging in the container"

soccerbot/launch/soccerbot.launch
=> added argument for use_sim_time

external/Dockerfile
=> Make webots build faster

.dockerignore, .idea/modules.xml, .idea/vcs.xml, .pre-commit-config.yaml, Dockerfile, soccer_strategy/src/communication/game_controller_receiver.py, soccer_strategy/src/communication/robot_state_pb2.py, soccer_webots/src/soccer_webots/messages_pb2.py, soccerbot/launch/soccerbot.launch, test_integration.py
=> Minor various fixes

test_integration.py
=> Add placeholder for "coords"

.github/workflows/docker_image_arm.yml, soccerbot/scripts/build_mxnet.sh, soccerbot/scripts/install_mxnet.sh
=> Change mxnet to pip

soccer_pycontrol/src/soccer_pycontrol/test_walking.py, soccer_webots/src/soccer_webots/bridge_ground_truth.py
=> fixes walk test in webots

soccer_pycontrol/src/soccer_pycontrol/path.py, soccer_pycontrol/src/soccer_pycontrol/path_section.py, soccer_pycontrol/src/soccer_pycontrol/test_walking.py, soccer_strategy/src/test_game_engine_2d.py
=> Fix small step

docker-compose.test.yaml, docker-compose.yaml, soccerbot/launch/modules/webots.launch, soccerbot/launch/soccerbot_multi.launch
=> add bez3 proto

Dockerfile
=> Address Dockerfile lint

docker-compose.robot.yaml, soccer_hardware/launch/soccer_hardware.launch, soccer_pycontrol/config/bez1.yaml, soccer_pycontrol/config/bez1_sim.yaml, soccer_pycontrol/src/soccer_pycontrol/soccerbot.py, soccer_pycontrol/src/soccer_pycontrol/test_walking.py, soccer_trajectories/src/soccer_trajectories.py
=> Initial bez tune

soccer_pycontrol/src/soccer_pycontrol/test_walking.py
=> Now pytests load parameters

soccer_common/maps/test.pgm, soccerbot/scripts/install_mxnet.sh
=> Bez vision fix

soccer_pycontrol/src/soccer_pycontrol/calibration.py, soccer_pycontrol/src/soccer_pycontrol/test_walking.py
=> Fix backwards calibration

soccer_pycontrol/src/soccer_pycontrol/soccerbot_ros.py, soccer_webots/src/soccer_webots/bridge_webots.py
=> small optimizations

docker-compose.robot.yaml, soccer_hardware/launch/soccer_hardware.launch, soccer_pycontrol/src/soccer_pycontrol/test_walking.py
https://github.com/utra-robosoccer/soccerbot/commit/f53c7dbf43c5221e3b6a0a0fa3c28b085ba8bf5c
=> Please read your code chnages before merging to master

Dockerfile
=> Fix ld library path

soccerbot/bags/view_rosbag.sh, soccerbot/bags/view_simulation.sh
=> Record 3d animation on each webots run

soccer_webots/src/soccer_webots/bridge_ground_truth.py, soccer_webots/src/soccer_webots/bridge_webots.py, soccerbot/bags/view_rosbag.sh, soccerbot/launch/soccerbot.launch
=> Fix yet another initial falling issue

soccer_pycontrol/src/soccer_pycontrol/soccerbot_ros.py, soccer_strategy/src/robot_controlled_3d.py, soccer_webots/src/soccer_webots/bridge_webots.py, soccerbot/launch/soccerbot.launch
=> More bug fixes

soccer_pycontrol/src/soccer_pycontrol/soccerbot_ros.py, soccer_strategy/src/strategy/interfaces/actions.py, soccer_strategy/src/strategy/strategy_dummy.py, soccer_strategy/src/team.py, soccer_strategy/src/test_game_engine_2d.py
=> More strategic kicking towards goal net

.github/workflows/test_integration.yml, docker-compose.test.kick.yaml, soccer_pycontrol/src/soccer_pycontrol/soccerbot_ros.py, soccer_strategy/src/strategy/interfaces/actions.py, soccer_strategy/src/strategy/strategy_dummy.py, soccer_strategy/src/team.py, soccer_strategy/src/test_game_engine_2d.py
=> Walk kick ci

docker-compose.game_controller.yaml, soccer_webots/config/teams.cfg
=> Create gamecontroller docker-compose

soccer_common/src/soccer_common/mock_ros.py, soccer_common/src/soccer_common/transformation.py, soccer_pycontrol/src/soccer_pycontrol/path.py, soccer_pycontrol/src/soccer_pycontrol/path_section.py, soccer_pycontrol/src/soccer_pycontrol/path_section_bezier.py, soccer_pycontrol/src/soccer_pycontrol/path_section_short.py, soccer_strategy/src/game_engine_2d.py, soccer_strategy/src/strategy/interfaces/actions.py, soccer_strategy/src/test_game_engine_2d.py
=> Fix strategy tests

soccer_strategy/src/test_game_engine_2d.py
=> FIx dummydummy

soccer_hardware/src/soccer_hardware/transmitter.py
=> Add sleep here for faster speeds

.idea/deployment.xml, .idea/sshConfigs.xml, .idea/webServers.xml
=> Update robot2 configs

docker-compose.robot.yaml, soccerbot/launch/modules/communication.launch, soccerbot/launch/soccerbot.launch
=> Fix game controller connection real robot

.github/workflows/docker_image_arm.yml, Dockerfile
=> Build arms

soccer_common/src/soccer_common/camera.py, soccer_common/src/soccer_common/test_common.py, soccer_common/src/soccer_common/transformation.py, soccer_object_detection/src/test_object_detection.py, soccer_object_localization/src/detector_fieldline.py, soccer_object_localization/src/detector_goalpost.py, soccer_object_localization/src/detector_objects.py, soccer_object_localization/src/test_object_localization.py, soccer_pycontrol/src/soccer_pycontrol/calibration.py, soccer_pycontrol/src/soccer_pycontrol/path.py, soccer_pycontrol/src/soccer_pycontrol/path_crotch.py, soccer_pycontrol/src/soccer_pycontrol/path_foot.py, soccer_pycontrol/src/soccer_pycontrol/path_section.py, soccer_pycontrol/src/soccer_pycontrol/path_section_bezier.py, soccer_pycontrol/src/soccer_pycontrol/path_section_short.py, soccer_pycontrol/src/soccer_pycontrol/soccerbot.py, soccer_pycontrol/src/soccer_pycontrol/soccerbot_controller.py, soccer_pycontrol/src/soccer_pycontrol/soccerbot_controller_ros.py, soccer_pycontrol/src/soccer_pycontrol/soccerbot_ros.py, soccer_pycontrol/src/soccer_pycontrol/test_special.py, soccer_pycontrol/src/soccer_pycontrol/test_walking.py, soccer_strategy/src/game_engine_2d.py, soccer_strategy/src/game_engine_scene.py, soccer_strategy/src/robot_controlled.py, soccer_strategy/src/robot_controlled_2d.py, soccer_strategy/src/robot_controlled_3d.py, soccer_webots/src/soccer_webots/bridge_ground_truth.py
I updated the transformation library completely, now everything is much easier to use
no more get euler from quaternion and quaternion from euler crap
Manx52 — Today at 11:08 PM
Nice
vuwij — Today at 11:08 PM
now its just t = Transformation(position=[1,2,3], quaternion=[1,2,3,4]) or 
t = Transformation(position=[1,2,3], euler=[1,2,3])
and you can use the transformation to literally convert to all formats, matrix, pos_theta, euler, ros message
approve plz
=> Update transformation library

.idea/soccerbot.iml, soccer_common/src/soccer_common/camera.py, soccer_common/src/soccer_common/pid.py, soccer_common/src/soccer_common/transformation.py
=> Documented camera

docker-compose.yaml, soccerbot/bags/view_simulation.sh
=> Graceful exit for webots

.gitignore, .idea/runConfigurations/Python_tests_for_test_integration_IntegrationTestPlaying_test_annotate_ball.xml, .idea/runConfigurations/Python_tests_for_test_integration_IntegrationTestPlaying_test_annotate_net.xml, .idea/runConfigurations/Python_tests_for_test_object_localization_TestObjectLocalization_test_fieldline_detection.xml, .idea/runConfigurations/Python_tests_for_test_object_localization_TestObjectLocalization_test_goalpost_detection.xml, .idea/runConfigurations/pytest_for_soccer_trajectories.xml, requirements.txt, soccer_object_localization/images/img0_-0.6805418953941712_-0.19657546078618005_-1.049088190788794.png, soccer_object_localization/images/img10_0.8641847711947435_0.18866567631476938_1.5249962322470259.png, soccer_object_localization/images/img11_0.0425320918554577_1.629702800190004_-2.915223713456875.png, soccer_object_localization/images/img12_1.109509427721366_2.330417857677584_-0.15655553984103276.png, soccer_object_localization/images/img13_-1.0020274648257552_-0.168873476816235_1.9748205753546078.png, soccer_object_localization/images/img14_-0.4107905429521215_2.4511358573282696_-0.8450607115290163.png, soccer_object_localization/images/img15_-1.4659361337858274_-0.5816355306389931_-0.502654929457147.png, soccer_object_localization/images/img16_-0.7853100428576383_-1.5254301032646078_-2.984049153805578.png, soccer_object_localization/images/img1_0.031962395374173_-0.8891447062075253_-2.658362073693127.png, soccer_object_localization/images/img2_-0.19940776631633783_0.9547434357596831_0.22595902027652404.png, soccer_object_localization/images/img2_-1.170645594381017_1.6704487675687467_-1.7207161315253598.png, soccer_object_localization/images/img3_-0.22778119664751917_0.7841084784936343_-0.3400951076777976.png, soccer_object_localization/images/img4_1.4594846269094557_1.495115016609354_-0.5027702268566427.png, soccer_object_localization/images/img5_-0.9405160632232356_-2.003114586611703_2.5573300113397712.png, soccer_object_localization/images/img6_-1.1265115856779753_-0.9692340250080882_-0.04040952933386244.png, soccer_object_localization/images/img7_-0.5656089451711844_-1.973872686616836_-2.1962339783923808.png, soccer_object_localization/images/img8_1.1242042670726646_0.5160025182546568_1.0373781171521408.png, soccer_object_localization/images/img9_-0.09214002310303626_-0.4566688643207222_-0.38770547262037836.png, soccer_object_localization/src/soccer_object_localization/test_object_localization.py, test_integration.py
=> Add datasets for collecting images

.idea/other.xml, bez3_description/urdf/bez3.urdf, bez3_description/urdf/bez3.xacro, soccer_common/src/soccer_common/mock_ros.py, soccer_pycontrol/config/bez1.yaml, soccer_pycontrol/config/bez1_sim.yaml, soccer_pycontrol/config/bez1_sim_pybullet.yaml, soccer_pycontrol/config/bez3_sim.yaml, soccer_pycontrol/config/bez3_sim_pybullet.yaml, soccer_pycontrol/src/soccer_pycontrol/calibration.py, soccer_pycontrol/src/soccer_pycontrol/joints.py, soccer_pycontrol/src/soccer_pycontrol/links.py, soccer_pycontrol/src/soccer_pycontrol/navigator.py, soccer_pycontrol/src/soccer_pycontrol/navigator_ros.py, soccer_pycontrol/src/soccer_pycontrol/path.py, soccer_pycontrol/src/soccer_pycontrol/path_foot.py, soccer_pycontrol/src/soccer_pycontrol/path_section.py, soccer_pycontrol/src/soccer_pycontrol/path_section_bezier.py, soccer_pycontrol/src/soccer_pycontrol/path_section_short.py, soccer_pycontrol/src/soccer_pycontrol/path_torso.py, soccer_pycontrol/src/soccer_pycontrol/soccerbot.py, soccer_pycontrol/src/soccer_pycontrol/soccerbot_ros.py, soccer_pycontrol/src/soccer_pycontrol/test_special.py, soccer_pycontrol/src/soccer_pycontrol/test_walking.py
=> Control pid tuning

.idea/deployment.xml, soccer_object_detection/src/soccer_object_detection/object_detect_node.py, soccer_object_detection/src/soccer_object_detection/test_object_detection.py, soccer_strategy/src/soccer_strategy/communication/game_controller_receiver.py
=> 701 don't detect ball in beginning and weird game controller recieve issue

docker-compose.dual.yaml, soccer_webots/src/soccer_webots/bridge_webots.py, soccerbot/config/robot_localization_ekf_map.yaml, soccerbot/launch/modules/communication.launch, soccerbot/launch/modules/localization.launch, soccerbot/launch/soccerbot.launch
now all 4 robots are moving in sim
=> fix namespace issues

Dockerfile
=> Downgrade cuda for functional run on Nvidia 3000 gpu

Dockerfile
=> Fix arm build

.github/workflows/auto_documentation.yml, .github/workflows/test_pytest.yml, .idea/vcs.xml, Dockerfile, docker-compose.yaml, requirements.txt
=> Optimize pytorch

soccer_pycontrol/src/soccer_pycontrol/test_walking.py
=> Added graph in test_imu_feedback for foot pressure sensor locations

soccer_pycontrol/src/soccer_pycontrol/test_walking.py
=> Gavin branch foot pressure sensor graph

soccer_localization/src/soccer_localization/field.py, soccer_localization/src/soccer_localization/field_lines_ukf.py, soccer_localization/src/soccer_localization/test_localization.py
=> Fix localization

bez1_description/src/base_footprint_to_torso.py, soccer_localization/src/soccer_localization/field_lines_ukf_ros.py, soccer_pycontrol/src/soccer_pycontrol/calibration.py, soccer_pycontrol/src/soccer_pycontrol/path.py, soccer_pycontrol/src/soccer_pycontrol/path_torso.py, soccer_pycontrol/src/soccer_pycontrol/soccerbot.py, soccer_pycontrol/src/soccer_pycontrol/soccerbot_ros.py, soccer_pycontrol/src/soccer_pycontrol/test_walking.py, soccerbot/rviz/soccerbot.rviz
=> Improve odometry more

soccer_pycontrol/src/soccer_pycontrol/path_section_short.py, soccer_strategy/src/soccer_strategy/team.py, soccer_strategy/src/soccer_strategy/test_game_engine_2d.py
=> Some strategy fixes

soccer_localization/src/soccer_localization/field.py, soccer_localization/src/soccer_localization/field_lines_ukf.py, soccer_localization/src/soccer_localization/field_lines_ukf_ros.py, soccer_localization/src/soccer_localization/test_localization.py, soccer_object_localization/src/soccer_object_localization/detector_goalpost.py, soccer_strategy/src/soccer_strategy/robot_controlled_3d.py, soccerbot/launch/modules/localization.launch
=> Much better localization parameters

soccer_localization/src/soccer_localization/field_lines_ukf.py, soccer_localization/src/soccer_localization/field_lines_ukf_ros.py, soccer_localization/src/soccer_localization/test_localization.py, soccer_strategy/src/soccer_strategy/robot_controlled_3d.py, soccer_strategy/src/soccer_strategy/strategy/strategy.py
=> Relocalization fall

soccer_localization/src/soccer_localization/field.py, soccer_localization/src/soccer_localization/field_lines_ukf.py, soccerbot/rviz/soccerbot.rviz
=> Start goal post assistance to localization

soccer_strategy/src/soccer_strategy/strategy/strategy_determine_side.py
=> fixed role assignment

soccer_strategy/src/soccer_strategy/strategy/utils.py, soccer_strategy/src/soccer_strategy/test_game_engine_2d.py
=> fix ball on line issue

soccer_strategy/src/soccer_strategy/game_engine_2d_scene.py, soccer_strategy/src/soccer_strategy/referee_2d.py, soccer_strategy/src/soccer_strategy/robot_controlled_2d.py, soccer_strategy/src/soccer_strategy/strategy/strategy_determine_side.py
- contact point detection issues
=> fix 2d strategy crash on score

soccer_strategy/src/soccer_strategy/game_engine_2d.py
=> player to player collision

.idea/deployment.xml, .idea/runConfigurations/Python_tests_for_test_walking_TestWalking_test_walk_1_real_robot.xml, .idea/sshConfigs.xml, .idea/webServers.xml, soccer_pycontrol/config/bez1.yaml, soccer_pycontrol/config/bez1_sim_pybullet.yaml, soccer_pycontrol/src/soccer_pycontrol/navigator.py, soccer_pycontrol/src/soccer_pycontrol/navigator_ros.py, soccer_pycontrol/src/soccer_pycontrol/path_section.py, soccer_pycontrol/src/soccer_pycontrol/soccerbot.py, soccer_pycontrol/src/soccer_pycontrol/test_walking.py, soccer_trajectories/src/soccer_trajectories/test_trajectory.py
=> Real robot testing

soccer_firmware/.settings/language.settings.xml, soccer_firmware/Core/Src/update_loop.c
=> off by one bug caused FW readings to be out of order
